### ISSUE TITLE
"Permissions not granted"

### ISSUE THREAD

**Issue by aiannacc** [davidADSP/SIMPLE#10]
Following the readme. After bringing up the docker image and installing the sushigo env, I try to run test.py and encounter this error:

```
> docker-compose exec app python3 test.py -d -g 1 -a base base human -e sushigo
Logging to logs
Saving base.zip PPO model...
Permissions not granted on zoo/sushigo/...
```

**Comment by aiannacc** [comment]
I tracked this down. It's because the ./zoo/sushigo directory didn't exist. Adding the directory manually fixes it.

Btw, when files.py catches the resulting IOError from the missing directory, it assumes it's a permissions error.

**Comment by davidADSP** [comment]
Yes that's right - I'll change the error message slightly to check that it also may not exist
