### ISSUE TITLE
Permissions not granted on zoo/sushigo/...

### ISSUE THREAD

**Issue by Timbobo16** [davidADSP/SIMPLE#3]
When running
`docker-compose exec app python3 test.py -d -g 1 -a base base human -e sushigo`
I get the error
`Logging to logs
Saving base.zip PPO model...
Permissions not granted on zoo/sushigo/...
ERROR: 1`

**Comment by agoldenduck** [comment]
I had the same problem. Solved it by creating the sushigo folder inside `app/zoo/`.
