### ISSUE TITLE
How to get the pretrained model

### ISSUE THREAD

**Issue by ybz21** [davidADSP/SIMPLE#8]
How  to get the pretrained model? Is the pretrained model training by setting the opponent_type='random'?

**Comment by davidADSP** [comment]
In the /zoo/pretrained/ folder there is a pre-trained /<game>/best_model.zip for each game, that can be copied up a directory (e.g. to /zoo/sushigo/best_model.zip) if you want to test playing against a pre-trained agent right away.

**Comment by ybz21** [comment]
> In the /zoo/pretrained/ folder there is a pre-trained //best_model.zip for each game, that can be copied up a directory (e.g. to /zoo/sushigo/best_model.zip) if you want to test playing against a pre-trained agent right away.

If I write a new game(env), how to train a pre-trained agent ?
